a = Artist.create!(name: "Artist Man")
a.songs.create!(title: "Song one")
a.songs.create!(title: "Song two")
a.songs.create!(title: "Song three")
a.songs.create!(title: "Song four")
a.songs.create!(title: "Song five")
a.songs.create!(title: "Song six")

b = Artist.create!(name: "Artist Woman")
b.songs.create!(title: "Song seven")
b.songs.create!(title: "Song eight")
b.songs.create!(title: "Song nine")
b.songs.create!(title: "Song ten")
b.songs.create!(title: "Song eleven")
b.songs.create!(title: "Song twelve")